### ISSUE TITLE
Issue while setting up network interface(Deploying OpenVINO)

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/edgeapps#11]
1. Client simulator and Edge node are connected through ethernet cables via usb to ethernet adapter.
2.  The default ethernet cable of both edge and client simulator is connected to open network.
3. When i run kubectl interfaceservice get worker-node(hostname of edge node), it should give two interface details right? but im getting only one interface details which is the of the default one.
4. How to get both interface details so that I can setup network interface to route the data from client simulator to edge node.
Note: I'm following the steps present in https://github.com/open-ness/specs/blob/master/doc/applications-onboard/openness-interface-service.md
<img width="960" alt="interface_error" src="https://user-images.githubusercontent.com/64581852/83994576-73a95880-a974-11ea-8385-2d1b5c60fefe.png">

**Comment by amr-mokhtar** [comment]
You need to use a NIC card that is compliant with kube-ovn.Try using a PCI-e NIC card and see if it becomes visible with the interfaceservice.

**Comment by JeevanCK7** [comment]
thank you @amr-mokhtar I swapped the ethernet connections. 
 Connected lab network connection to usb-to-ethernet adapter and point to point connection to NIC card. It working now
