### ISSUE TITLE
OpenVINO Consumer App 20.06 - Waiting: CrashLoopBackOff

### ISSUE THREAD

**Issue by vaghesh** [open-ness/edgeapps#20]
For OpenVINO Edgeapp, we followed the document to build the producer and consumer docker images. The build was successful. 
After deploying using kubectl, the openvino-cons-app is created. But it goes into CrashLoopBackOff

Logs from openvino-cons-app in openvino-cons-app
```
[setupvars.sh] OpenVINO environment initialized
 command-line-arguments
./openvino.go:64:9: undefined: err
./openvino.go:65:16: undefined: err
./openvino.go:70:9: undefined: err
./openvino.go:71:16: undefined: err
./start.sh: line 10: fg: no job control ```

**Comment by ishanVshah** [comment]
@vaghesh  try with previous repository.

**Comment by amr-mokhtar** [comment]
Hi @vaghesh, I am replicating this issue internally. Will get back to you with a proposed fix. It sounds like a variable definition is missing.

**Comment by vaghesh** [comment]
> @vaghesh try with previous repository.

Thank you. Previous version is working.

**Comment by amr-mokhtar** [comment]
This issue should have been fixed by this PR: https://github.com/open-ness/edgeapps/pull/23
