### ISSUE TITLE
Error while Onboarding EAA Sample Application

### ISSUE THREAD

**Issue by sushantsj** [open-ness/edgeapps#28]
While Deploying Consumer and Producer Sample Application the pod is not running with error of ErrImagePull
Can someone tell whats the issue

**Comment by amr-mokhtar** [comment]
Hi @sushantsj! This indicates that Kubernetes is unable to pull from docker hub/registry or find the docker image locally.
1. If you are building the docker images locally, you need to build them on all the worker nodes.
2. If you are using the OpenNESS docker registry, you should make sure that they are tagged and pushed to the local registry.

**Comment by sushantsj** [comment]
Thank you @amr-mokhtar  the issue is resolved now
