### ISSUE TITLE
Pod Liveliness Issue

### ISSUE THREAD

**Issue by avi1810** [open-ness/edgeapps#4]
The time frame set for the producer and consumer pods are very less. Due to which, the testing is getting affected. Also testing steps are not very clear to us. Could you please help us how to check the output of the sample consumer producer app?

**Comment by amr-mokhtar** [comment]
> The time frame set for the producer and consumer pods are very less. Due to which, the testing is getting affected.

Hi @avi1810, Can you elaborate more?
Are you talking about sample producer-consumer apps? Is it Network-Edge deployment? What do you mean by *testing getting affected*?

**Comment by avi1810** [comment]
Yes, I am discussing about the network-edge deployment of sample producer-consumer app. 
About testing, are we only supposed to check the logs in which I am getting 'sending notification' from the producer side and 'received notification' from the consumer side? And producer and  consumer pods are also terminating after 3 and 2 minutes respectively. Is there anyother way to test this application?

**Comment by amr-mokhtar** [comment]
The sample apps is provided as a means to showcase how EAA APIs can be consumed from an edge application. The two apps are quite simple, the consumer app sends out a notification on fixed intervals and the consumer apps receives these notifications and print them. To verify check the logs of the apps. Full details on deploying the apps and verify their execution is covered in this section -> https://github.com/open-ness/specs/blob/master/doc/applications-onboard/network-edge-applications-onboarding.md#onboarding-sample-application

**Comment by avi1810** [comment]
Okay, I got it now. I will test it again. Thanks for your support. You may close this now.
