### ISSUE TITLE
Guide for making an application consumer and producer

### ISSUE THREAD

**Issue by git-abhijit** [open-ness/edgeapps#63]
Hi, 
Is there any development guide in which steps are provided to make my application as a producer and consumer application. 
Need to make my sample application producer app and consumer app. 
Thanks
Abhijit

**Comment by cjnolan** [comment]
Hi @git-abhijit, please see https://github.com/open-ness/specs/blob/master/doc/applications/openness_appguide.md for details on developing and porting applications to OpenNESS

**Comment by git-abhijit** [comment]
Thanks cjnolan for sharing. Will go through the same. If any queries post that will raise a new request. 
Regards.
Abhijit
