### ISSUE TITLE
JSON files for various API's supported in Openness.

### ISSUE THREAD

**Issue by git-abhijit** [open-ness/edgeapps#64]
Hi , Can I get the sample json files for the various REST API's supported in Openness or if its already there pls share the details for the same.? Like for AF, EAA, EDNS etc. 
Regards
Abhijit

**Comment by cjnolan** [comment]
Hi @git-abhijit, the supported REST APIs are outlined here: https://www.openness.org/developers#apidoc

**Comment by git-abhijit** [comment]
Thanks @cjnolan  for sharing the details. 
Is it feasible to get the sample JSON files which were used for testing. 
It will be really helpful. 
Regards
Abhijit

**Comment by cjnolan** [comment]
Hi @git-abhijit the schemas for the APIs on https://www.openness.org/developers#apidoc are located in https://github.com/open-ness/specs/tree/master/schema

**Comment by git-abhijit** [comment]
Thanks @cjnolan for sharing the details.
